spring:
  datasource:
    url: jdbc:postgresql://<Replace with your PostgreSQL database endpoint>
    username: <Replace with your PostgreSQL database credentials>
    password: <Replace with your PostgreSQL database credentials>
    hikari:
      maximum-pool-size: 100
      minimum-idle: 20
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8081

logging:
  level:
    com.multitenancy.table: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: TRACE